// testConstants.js
import { DOM_IDS } from '../../findviz/static/js/constants/DomIds.js';

export const TEST_DOM_IDS = {
    AVERAGE: {
        AVERAGE_FORM: `#${DOM_IDS.AVERAGE.AVERAGE_FORM}`,
        ERROR_MESSAGE: `#${DOM_IDS.AVERAGE.ERROR_MESSAGE}`,
        LEFT_EDGE: `#${DOM_IDS.AVERAGE.LEFT_EDGE}`,
        MODAL_BUTTON: `#${DOM_IDS.AVERAGE.MODAL_BUTTON}`,
        RIGHT_EDGE: `#${DOM_IDS.AVERAGE.RIGHT_EDGE}`,
        SPINNER_OVERLAY: `#${DOM_IDS.AVERAGE.SPINNER_OVERLAY}`,
        SPINNER_WHEEL: `#${DOM_IDS.AVERAGE.SPINNER_WHEEL}`,
        SUBMIT_AVERAGE: `#${DOM_IDS.AVERAGE.SUBMIT_AVERAGE}`,
    },
    CORRELATE: {
        CORRELATE_FORM: `#${DOM_IDS.CORRELATE.CORRELATE_FORM}`,
        MODAL_BUTTON: `#${DOM_IDS.CORRELATE.MODAL_BUTTON}`,
        NEGATIVE_LAG: `#${DOM_IDS.CORRELATE.NEGATIVE_LAG}`,
        POSITIVE_LAG: `#${DOM_IDS.CORRELATE.POSITIVE_LAG}`,
        SUBMIT_CORRELATE: `#${DOM_IDS.CORRELATE.SUBMIT_CORRELATE}`,
        TIMECOURSE_SELECT: `#${DOM_IDS.CORRELATE.TIMECOURSE_SELECT}`
    },
    DISTANCE: {
        CONTAINER: `#${DOM_IDS.DISTANCE.CONTAINER}`,
        DISTANCE_FORM: `#${DOM_IDS.DISTANCE.DISTANCE_FORM}`,
        MODAL_BUTTON: `#${DOM_IDS.DISTANCE.MODAL_BUTTON}`,
        PLOT: `#${DOM_IDS.DISTANCE.PLOT}`,
        POPOVER: `#${DOM_IDS.DISTANCE.POPOVER}`,
        REMOVE_DISTANCE_BUTTON: `#${DOM_IDS.DISTANCE.REMOVE_DISTANCE_BUTTON}`,
    },
    UPLOAD: {
        ERROR_MESSAGE: `#${DOM_IDS.FILE_UPLOAD.ERROR_MESSAGE}`,
        MODAL: `#${DOM_IDS.FILE_UPLOAD.MODAL}`,
        MODAL_BUTTON: `#${DOM_IDS.FILE_UPLOAD.MODAL_BUTTON}`,
        SUBMIT_BUTTON: `#${DOM_IDS.FILE_UPLOAD.SUBMIT_BUTTON}`,
        NIFTI: {
            FUNC: `#${DOM_IDS.FILE_UPLOAD.FMRI.NIFTI.FUNC}`,
            ANAT: `#${DOM_IDS.FILE_UPLOAD.FMRI.NIFTI.ANAT}`,
            MASK: `#${DOM_IDS.FILE_UPLOAD.FMRI.NIFTI.MASK}`
        },
        GIFTI: {
            LEFT_FUNC: `#${DOM_IDS.FILE_UPLOAD.FMRI.GIFTI.LEFT_FUNC}`,
            RIGHT_FUNC: `#${DOM_IDS.FILE_UPLOAD.FMRI.GIFTI.RIGHT_FUNC}`,
            LEFT_MESH: `#${DOM_IDS.FILE_UPLOAD.FMRI.GIFTI.LEFT_MESH}`,
            RIGHT_MESH: `#${DOM_IDS.FILE_UPLOAD.FMRI.GIFTI.RIGHT_MESH}`
        },
        CIFTI: {
            DTSERIES: `#${DOM_IDS.FILE_UPLOAD.FMRI.CIFTI.DTSERIES}`,
            LEFT_MESH: `#${DOM_IDS.FILE_UPLOAD.FMRI.CIFTI.LEFT_MESH}`,
            RIGHT_MESH: `#${DOM_IDS.FILE_UPLOAD.FMRI.CIFTI.RIGHT_MESH}`
        },
        TAB_NIFTI: '#nifti-tab',
        TAB_GIFTI: '#gifti-tab',
        TAB_CIFTI: '#cifti-tab',
        TASK: {
            FILE: `#${DOM_IDS.FILE_UPLOAD.TASK.FILE}`,
            TR: `#${DOM_IDS.FILE_UPLOAD.TASK.TR}`,
            SLICETIME: `#${DOM_IDS.FILE_UPLOAD.TASK.SLICETIME}`
        },
        TS: {
            ADD_TS: `#${DOM_IDS.FILE_UPLOAD.TS.ADD_TS}`,
            FILE: `.${DOM_IDS.FILE_UPLOAD.TS.FILE}`,
            HEADER: `.${DOM_IDS.FILE_UPLOAD.TS.HEADER}`,
            LABEL: `.${DOM_IDS.FILE_UPLOAD.TS.LABEL}`,
            REMOVE_BUTTON: `.${DOM_IDS.FILE_UPLOAD.TS.REMOVE_BUTTON}`,
        },
        SCENE: {
            BUTTON: `#${DOM_IDS.FILE_UPLOAD.SCENE.BUTTON}`,
            FILE: `#${DOM_IDS.FILE_UPLOAD.SCENE.FILE}`
        }
      },
    FMRI: {
        COORDINATE: {
            WORLD_X: `#${DOM_IDS.FMRI.COORDINATE.WORLD_X}`,
            WORLD_Y: `#${DOM_IDS.FMRI.COORDINATE.WORLD_Y}`,
            WORLD_Z: `#${DOM_IDS.FMRI.COORDINATE.WORLD_Z}`,
            VOXEL_X: `#${DOM_IDS.FMRI.COORDINATE.VOXEL_X}`,
            VOXEL_Y: `#${DOM_IDS.FMRI.COORDINATE.VOXEL_Y}`,
            VOXEL_Z: `#${DOM_IDS.FMRI.COORDINATE.VOXEL_Z}`,
            VERTEX_NUMBER: `#${DOM_IDS.FMRI.COORDINATE.VERTEX_NUMBER}`,
            SELECTED_HEMISPHERE: `#${DOM_IDS.FMRI.COORDINATE.SELECTED_HEMISPHERE}`
        },
        CONTAINER: `#${DOM_IDS.FMRI.VISUALIZATION_CONTAINER}`,
        NIFTI_CONTAINER: {
            SLICE_1: `#${DOM_IDS.FMRI.NIFTI_CONTAINERS.SLICE_1_CONTAINER}`,
            SLICE_2: `#${DOM_IDS.FMRI.NIFTI_CONTAINERS.SLICE_2_CONTAINER}`,
            SLICE_3: `#${DOM_IDS.FMRI.NIFTI_CONTAINERS.SLICE_3_CONTAINER}`
        },
        GIFTI_CONTAINER: {
            COLORBAR: `#${DOM_IDS.FMRI.GIFTI_CONTAINERS.COLORBAR}`,
            SURFACE_CONTAINER: `#${DOM_IDS.FMRI.GIFTI_CONTAINERS.SURFACE_CONTAINER}`,
            LEFT_SURFACE_CONTAINER: `#${DOM_IDS.FMRI.GIFTI_CONTAINERS.LEFT_SURFACE_CONTAINER}`,
            RIGHT_SURFACE_CONTAINER: `#${DOM_IDS.FMRI.GIFTI_CONTAINERS.RIGHT_SURFACE_CONTAINER}`
        },
        PREPROCESSING_OPTIONS: {
            ENABLE_DETRENDING: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.ENABLE_DETRENDING}`,
            ENABLE_FILTERING: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.ENABLE_FILTERING}`,
            ENABLE_NORMALIZATION: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.ENABLE_NORMALIZATION}`,
            ENABLE_SMOOTHING: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.ENABLE_SMOOTHING}`,
            FILTER_LOW_CUT: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.FILTER_LOW_CUT}`,
            FILTER_HIGH_CUT: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.FILTER_HIGH_CUT}`,
            FILTER_TR: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.FILTER_TR}`,
            SELECT_MEAN_CENTER: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.SELECT_MEAN_CENTER}`,
            SELECT_Z_SCORE: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.SELECT_Z_SCORE}`,
            SMOOTHING_FWHM: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.SMOOTHING_FWHM}`,
            SUBMIT_PREPROCESS_BUTTON: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.SUBMIT_PREPROCESS_BUTTON}`,
            RESET_PREPROCESS_BUTTON: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.RESET_PREPROCESS_BUTTON}`,
            ERROR_MESSAGE_PREPROCESS: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.ERROR_MESSAGE_PREPROCESS}`,
            PREPROCESS_ALERT: `#${DOM_IDS.FMRI.PREPROCESSING_OPTIONS.PREPROCESS_ALERT}`
        },
        VISUALIZATION_OPTIONS: {
            COLOR_RANGE_SLIDER_FORM: '#form-color-range',
            COLORMAP_DROPDOWN: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.COLORMAP_DROPDOWN}`,
            COLORMAP_DROPDOWN_MENU: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.COLORMAP_DROPDOWN_MENU}`,
            COLORMAP_DROPDOWN_TOGGLE: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.COLORMAP_DROPDOWN_TOGGLE}`,
            MONTAGE_POPOVER: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.MONTAGE_POPOVER}`,
            MONTAGE_SLICE_SELECT: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.MONTAGE_SLICE_SELECT}`,
            MONTAGE_SLICE_SLIDER_CONTAINER: `#slice-sliders`,
            MONTAGE_SLICE_1_SLIDER: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.MONTAGE_SLICE_1_SLIDER}`,
            MONTAGE_SLICE_2_SLIDER: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.MONTAGE_SLICE_2_SLIDER}`,
            MONTAGE_SLICE_3_SLIDER: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.MONTAGE_SLICE_3_SLIDER}`,
            OPACITY_SLIDER_FORM: '#form-opacity',
            RESET_SLIDER_BUTTON: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.RESET_SLIDER_BUTTON}`,
            REVERSE_COLORBAR_TOGGLE: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.REVERSE_COLORBAR_TOGGLE}`,
            THRESHOLD_SLIDER: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.THRESHOLD_SLIDER}`,
            THRESHOLD_SLIDER_FORM: '#form-threshold',
            TOGGLE_VIEW_BUTTON: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.TOGGLE_VIEW_BUTTON}`,
            TR_CONVERT_FORM: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.TR_CONVERT_FORM}`,
            TR_CONVERT_BUTTON: `#${DOM_IDS.FMRI.VISUALIZATION_OPTIONS.TR_CONVERT_BUTTON}`,
        }
    },
    TIME_SLIDER: {
        TIME_SLIDER_CONTAINER: `#time-slider-container`,
        TIME_SLIDER: `#${DOM_IDS.TIME_SLIDER.TIME_SLIDER}`,
        TIME_POINT_DISPLAY: `#${DOM_IDS.TIME_SLIDER.TIME_POINT_DISPLAY}`
    },
    TIMECOURSE: {
        ANNOTATE: {
            ENABLE_ANNOTATE: `#${DOM_IDS.TIMECOURSE.ANNOTATE.ENABLE_ANNOTATE}`,
            LEFT_MOVE_ANNOTATE: `#${DOM_IDS.TIMECOURSE.ANNOTATE.LEFT_MOVE_ANNOTATE}`,
            RIGHT_MOVE_ANNOTATE: `#${DOM_IDS.TIMECOURSE.ANNOTATE.RIGHT_MOVE_ANNOTATE}`,
            HIGHLIGHT_ANNOTATE: `#${DOM_IDS.TIMECOURSE.ANNOTATE.HIGHLIGHT_ANNOTATE}`,
            UNDO_ANNOTATE: `#${DOM_IDS.TIMECOURSE.ANNOTATE.UNDO_ANNOTATE}`,
            REMOVE_ANNOTATE: `#${DOM_IDS.TIMECOURSE.ANNOTATE.REMOVE_ANNOTATE}`,
            POPOVER: `#${DOM_IDS.TIMECOURSE.ANNOTATE.POPOVER}`
        },
        FMRI: {
            ENABLE_FMRI_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.FMRI.ENABLE_FMRI_TIMECOURSE}`,
            FREEZE_FMRI_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.FMRI.FREEZE_FMRI_TIMECOURSE}`,
            FREEZE_ICON: `#${DOM_IDS.TIMECOURSE.FMRI.FREEZE_ICON}`,
            REMOVE_FMRI_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.FMRI.REMOVE_FMRI_TIMECOURSE}`,
            UNDO_FMRI_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.FMRI.UNDO_FMRI_TIMECOURSE}`
        },
        TIME_COURSE_CONTAINER: `#${DOM_IDS.TIMECOURSE.TIME_COURSE_CONTAINER}`,
        TIME_COURSE_PLOT: `#${DOM_IDS.TIMECOURSE.TIME_COURSE_PLOT}`,
        LINE_PLOT_OPTIONS: {
            COLOR_SELECT: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.COLOR_SELECT}`,
            CONVOLUTION_CHECKBOX: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.CONVOLUTION_CHECKBOX}`,
            CONSTANT_SHIFT_INCREASE: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.CONSTANT_SHIFT_INCREASE}`,
            CONSTANT_SHIFT_DECREASE: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.CONSTANT_SHIFT_DECREASE}`,
            CONSTANT_SHIFT_RESET: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.CONSTANT_SHIFT_RESET}`,
            MARKER_SELECT: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.MARKER_SELECT}`,
            OPACITY_SLIDER: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.OPACITY_SLIDER}`,
            OPACITY_SLIDER_CONTAINER: `#ts-opacity-slider-container`,
            SELECT_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.SELECT_TIMECOURSE}`,
            WIDTH_SLIDER: `#${DOM_IDS.TIMECOURSE.LINE_PLOT_OPTIONS.WIDTH_SLIDER}`,
            WIDTH_SLIDER_CONTAINER: `#ts-width-slider-container`,
        },
        PEAK_FINDER: {
            POPOVER: `#${DOM_IDS.TIMECOURSE.PEAK_FINDER.POPOVER}`,
            SELECT_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.PEAK_FINDER.SELECT_TIMECOURSE}`,
            SUBMIT_PEAK_FINDER: `#${DOM_IDS.TIMECOURSE.PEAK_FINDER.SUBMIT_PEAK_FINDER}`,
            PEAK_HEIGHT: '#peak-height'
        },
        PREPROCESSING_OPTIONS: {
            ENABLE_DETRENDING: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.ENABLE_DETRENDING}`,
            ENABLE_NORMALIZATION: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.ENABLE_NORMALIZATION}`,
            ERROR_MESSAGE_PREPROCESS: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.ERROR_MESSAGE_PREPROCESS}`,
            RESET_PREPROCESS_BUTTON: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.RESET_PREPROCESS_BUTTON}`,
            SELECT_MEAN_CENTER: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.SELECT_MEAN_CENTER}`,
            SELECT_Z_SCORE: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.SELECT_Z_SCORE}`,
            SELECT_TIMECOURSE: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.SELECT_TIMECOURSE}`,
            SUBMIT_PREPROCESS_BUTTON: `#${DOM_IDS.TIMECOURSE.PREPROCESSING_OPTIONS.SUBMIT_PREPROCESS_BUTTON}`,
        },
        PREPROCESS_ALERT: `#${DOM_IDS.TIMECOURSE.PREPROCESS_ALERT}`,
        VISUALIZATION_OPTIONS: {
            TOGGLE_CONVOLUTION: `#${DOM_IDS.TIMECOURSE.VISUALIZATION_OPTIONS.TOGGLE_CONVOLUTION}`,
        }
    }
}