name: FINDVIZ Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
 
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            
      - name: Install dependencies
        run: |
          poetry install
          
      - name: Run pytest
        run: |
          poetry install
          mkdir -p pytest-results
          poetry run pytest --junitxml=pytest-results/junit.xml
          
      - name: Upload pytest results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-results
          path: pytest-results/