name: FINDVIZ Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
 
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            
      - name: Install dependencies
        run: |
          poetry install
          
      - name: Run pytest
        run: |
          poetry run pytest --junitxml=pytest-results/junit.xml
          
      - name: Upload pytest results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: pytest-results
          path: pytest-results/

  cypress:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            
      - name: Install Python dependencies
        run: |
          poetry install
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install Cypress dependencies
        run: |
          npm ci
          
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run test:e2e
          
      - name: Upload Cypress results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/videos/
            cypress/screenshots/
